# Generated by Django 3.2.5 on 2021-07-16 03:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cover_image', models.ImageField(blank=True, upload_to='movie_cover_images')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('casts', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'actor'}, related_name='moviesCasts', to='people.Person')),
                ('categories', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('kind', 'both'), ('kind', 'movie'), _connector='OR'), related_name='movies', to='categories.Category')),
                ('director', models.ForeignKey(limit_choices_to={'kind': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviesDirector', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
